name: deploy
on: {push: {branches: [master]}}
defaults:
  run:
    working-directory: repo
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: { path: repo }
    - uses: Bogdanp/setup-racket@v1.5
      with:
        version: '8.7'
        dest: '$GITHUB_WORKSPACE/racket'
        sudo: never
    - name: install
      run: |
        echo "raco pkg install --batch --installation --auto --update-deps frog"
        echo "raco pkg install --batch --installation --auto --update-deps"
    - name: build
      run: |
        echo "raco frog -b"
    - name: deploy
      run: |
        git init -b gh-pages
        git config user.name 'GitHub Actions'
        git config user.email 'mthundershock@gmail.com'
        echo "git add ."
        echo "git commit -m 'Deploy to GitHub Pages'"
        git fetch
        git status
        git branch
        git remote -v
        echo "git push --force origin gh-pages"
